### ISSUE TITLE
Use inner exception for better error messages

### ISSUE THREAD

**Issue by xXBuilderBXx** [mcwwi/lib-rcon#1]
Hi im back and have been using this lib for quite awhile now one thing i noticed is the exception in try catch function is only returning "One or more errors occurred" not sure if this is intentional but it would be better to use the inner exception which gives better error messages such as "No such host is known" if ip is invalid.

Fyi some error messages expose the IP address in the error message.

```
if (e.InnerException == null)
    LastTCPError = e.Message;
else
    LastTCPError = e.InnerException.Message;

**Comment by chiefmultihat** [comment]
Do you want to expose the ip?  I willlook into and expose the inner exceptions to drill in.  The exception handling is to help with debugging, but the whole library isn't bolted down with great error handling yet.

**Comment by chiefmultihat** [comment]
A newer library/repo on the way - will try to address this issue there.
